evarobot library: IMI2C Class Reference
IMI2C Class Reference
#include <IMI2C.h>
Public Member Functions
IMI2C ()
Constructor.
IMI2C (unsigned char u_c_device_address, string str_i2c_file_name, sem_t *mutex)
Constructor.
~IMI2C (void)
int WriteDataByte (unsigned char u_c_register_address, unsigned char u_c_data)
Function to write byte data into a register of an I2C device.
int ReadDataByte (unsigned char u_c_register_address, unsigned char &u_c_data)
Function to read byte data from a register of an I2C device.
Private Member Functions
int OpenI2C ()
Open an I2C device.
int CloseI2C (int i_i2cfd)
Close an I2C device.
Private Attributes
string str_i2c_file_name
i2c device name e.g."/dev/i2c-0" or "/dev/i2c-1"
unsigned char u_c_device_adress
sem_t * mutex
Detailed Description
Definition at line 43 of file IMI2C.h.
Constructor & Destructor Documentation
IMI2C::IMI2C ()
Constructor.
Definition at line 16 of file IMI2C.cpp.
References OpenI2C(), str_i2c_file_name, and u_c_device_adress.
IMI2C::IMI2C (unsigned char u_c_device_address, string str_i2c_file_name, sem_t * mutex)
Constructor.
Parameters
u_c_device_address i2c device address
str_i2c_file_name i2c device driver name
* mutex
Definition at line 32 of file IMI2C.cpp.
References mutex, OpenI2C(), str_i2c_file_name, and u_c_device_adress.
IMI2C::~IMI2C (void)
Definition at line 45 of file IMI2C.cpp.
Member Function Documentation
int IMI2C::CloseI2C (int i_i2cfd) private
Close an I2C device.
Parameters
i_i2cfd <0 if there ise an error
Return values
>=0 no error
Definition at line 80 of file IMI2C.cpp.
Referenced by ReadDataByte(), and WriteDataByte().
int IMI2C::OpenI2C () private
Open an I2C device.
<0 if there ise an error
Return values
>=0 no error
Definition at line 59 of file IMI2C.cpp.
References str_i2c_file_name.
Referenced by IMI2C(), ReadDataByte(), and WriteDataByte().
int IMI2C::ReadDataByte (unsigned char u_c_register_address, unsigned char & u_c_data)
Function to read byte data from a register of an I2C device.
Detailed
Parameters
u_c_register_address
& u_c_data Okunan değerdir. <0 if there ise an error
Return values
>=0 no error
Definition at line 149 of file IMI2C.cpp.
References CloseI2C(), OpenI2C(), and u_c_device_adress.
Referenced by IMEIO::GetPinAValue(), and IMEIO::GetPinBValue().
int IMI2C::WriteDataByte (unsigned char u_c_register_address, unsigned char u_c_data)
Function to write byte data into a register of an I2C device.
Parameters
u_c_register_address
u_c_data <0 if there ise an error
Return values
>=0 no error
Definition at line 102 of file IMI2C.cpp.
References CloseI2C(), OpenI2C(), and u_c_device_adress.
Referenced by IMEIO::SetPinADirection(), IMEIO::SetPinAValue(), IMEIO::SetPinBDirection(), and IMEIO::SetPinBValue().
Member Data Documentation
sem_t* IMI2C::mutex private
Definition at line 169 of file IMI2C.h.
Referenced by IMI2C().
string IMI2C::str_i2c_file_name private
i2c device name e.g."/dev/i2c-0" or "/dev/i2c-1"
Definition at line 164 of file IMI2C.h.
Referenced by IMI2C(), and OpenI2C().
unsigned char IMI2C::u_c_device_adress private
Definition at line 167 of file IMI2C.h.
Referenced by IMI2C(), ReadDataByte(), and WriteDataByte().
The documentation for this class was generated from the following files:
include/IMI2C.h
src/IMI2C.cpp