evarobot library: IMUM6 Class Reference
IMUM6 Class Reference
#include <IMUM6.h>
Classes
struct PACKET_TYPE
struct REGISTERS
struct UM6_DATA
union UNION32
Public Member Functions
IMUM6 (IMSerial *p_imserial)
Constructor.
bool isReceivedData (char *p_c_start_bits, int i_length)
Brief.
bool isCommandCompleted () const
Brief.
bool CheckData ()
Brief.
void GetFWVersion ()
Brief.
int SetBaudRate (long l_baudrate)
Brief.
int SetFrequency (int i_frequency)
Brief.
int SetGPSBaudrate (long l_baudrate)
Brief.
int SetDetailedSatelliteStatusTrasmission (bool b_status)
Brief.
int SetSatelliteSummaryTrasmission (bool b_status)
Brief.
int SetGPSCourseVelocityTrasmission (bool b_status)
Brief.
int SetGPSRelativePositionTrasmission (bool b_status)
Brief.
int SetGPSPositionTransmission (bool b_status)
Brief.
int SetTemperatureMeasurementTransmission (bool b_status)
Brief.
int SetCovarianceMatrixTransmission (bool b_status)
Brief.
int SetEulerAngleTransmission (bool b_status)
Brief.
int SetQuaternionTransmission (bool b_status)
Brief.
int SetProcessedMagnetometerTransmission (bool b_status)
Brief.
int SetProcessedAccelerometerTransmission (bool b_status)
Brief.
int SetProcessedGyroTransmission (bool b_status)
Brief.
int SetRawMagnetometerTransmission (bool b_status)
Brief.
int SetRawAccelerometerTransmission (bool b_status)
Brief.
int SetRawGyroTransmission (bool b_status)
Brief.
int SetMode (bool b_mode)
Brief.
int SetPPSTiming (bool b_status)
Brief.
int SetQuaterninonState (bool b_status)
Brief.
int SetGyroCalibration (bool b_status)
Brief.
int SetEKFAccelerometerUpdates (bool b_status)
Brief.
int SetEKFMagnetometerUpdates (bool b_status)
Brief.
bool GetRawData (IMUM6::UM6_DATA &data)
Brief.
int ProcessData (vector< int > &T_i_registers)
Brief.
int32_t GetDataRegister (int i_register) const
Brief.
int SetCommand (int i_register)
Brief.
Public Attributes
struct IMUM6::UM6_DATA um6_data
Private Member Functions
bool ParseData ()
Brief.
void StoreData ()
Brief.
void SetRegisterPinValue (int32_t &i_register, int i_pin_no, int i_count_of_pins, char c_value)
Brief.
int SetRegister32bitValue (int i_register, float f_data)
Brief.
int SetRegister32bitValue (int i_register, int32_t i_data)
Brief.
int SetRegister16bitValue (int i_register, int16_t i_data)
Brief.
int SetRegister16bitValue (int i_register, int16_t *p_i_data)
Brief.
int CalculateChecksum ()
Brief.
Private Attributes
int32_t i_data_registers [85]
int32_t i_communication_register
int32_t i_misc_config_register
char c_input_buffer [500]
char c_start_bits [3]
bool b_command_complete
list< char > T_c_stored_data
list< char > T_c_serial_log
bool b_incomplete_packet
int i_incomplete_no
int i_start_bit_counter
int i_buffer_read_index
IMSerial * p_imserial
Detailed Description
Definition at line 31 of file IMUM6.h.
Constructor & Destructor Documentation
IMUM6::IMUM6 (IMSerial * p_imserial)
Constructor.
Parameters
\param
Definition at line 10 of file IMUM6.cpp.
References b_command_complete, b_incomplete_packet, c_start_bits, i_buffer_read_index, i_communication_register, i_incomplete_no, i_misc_config_register, i_start_bit_counter, and p_imserial.
Member Function Documentation
int IMUM6::CalculateChecksum () private
Brief.
Detailed
Parameters
\return
Definition at line 1154 of file IMUM6.cpp.
bool IMUM6::CheckData ()
Brief.
Detailed
Parameters
\return
Definition at line 231 of file IMUM6.cpp.
References IMUM6::UM6_DATA::c_adress, IMUM6::UM6_DATA::c_checksum, IMUM6::UM6_DATA::c_databytes, IMUM6::UM6_DATA::c_PT, c_start_bits, IMUM6::PACKET_TYPE::i_size_of_data, IMUM6::UM6_DATA::packet_type, and um6_data.
int32_t IMUM6::GetDataRegister (int i_register) const
Brief.
Detailed
Parameters
\return
Definition at line 1106 of file IMUM6.cpp.
References i_data_registers.
void IMUM6::GetFWVersion ()
Brief.
Detailed
Parameters
\return
bool IMUM6::GetRawData (IMUM6::UM6_DATA & data)
Brief.
Detailed
Parameters
\return
Definition at line 144 of file IMUM6.cpp.
References ParseData(), and um6_data.
bool IMUM6::isCommandCompleted () const
Brief.
Detailed
Parameters
\return
Definition at line 1162 of file IMUM6.cpp.
References b_command_complete.
bool IMUM6::isReceivedData (char * p_c_start_bits, int i_length)
Brief.
Detailed
Parameters
\return
Definition at line 157 of file IMUM6.cpp.
References i_start_bit_counter, and T_c_stored_data.
Referenced by ParseData().
bool IMUM6::ParseData () private
Brief.
Detailed
Parameters
\return
Definition at line 27 of file IMUM6.cpp.
References b_incomplete_packet, IMUM6::UM6_DATA::c_adress, IMUM6::UM6_DATA::c_checksum, IMUM6::UM6_DATA::c_databytes, IMUM6::UM6_DATA::c_PT, c_start_bits, IMUM6::PACKET_TYPE::i_batch_length, IMUM6::PACKET_TYPE::i_command_failed, i_incomplete_no, IMUM6::PACKET_TYPE::i_packet_has_data, IMUM6::PACKET_TYPE::i_packet_is_batch, IMUM6::PACKET_TYPE::i_size_of_data, isReceivedData(), IMUM6::UM6_DATA::packet_type, StoreData(), T_c_stored_data, and um6_data.
Referenced by GetRawData().
int IMUM6::ProcessData (vector< int > & T_i_registers)
Brief.
Detailed
Parameters
\return
Definition at line 1043 of file IMUM6.cpp.
References b_command_complete, IMUM6::UNION32::c, IMUM6::UM6_DATA::c_adress, IMUM6::UM6_DATA::c_databytes, IMUM6::UNION32::i, IMUM6::PACKET_TYPE::i_batch_length, IMUM6::PACKET_TYPE::i_command_failed, i_data_registers, IMUM6::PACKET_TYPE::i_packet_has_data, IMUM6::PACKET_TYPE::i_packet_is_batch, IMUM6::UM6_DATA::packet_type, and um6_data.
int IMUM6::SetBaudRate (long l_baudrate)
Brief.
Detailed
Parameters
\return
Definition at line 331 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetCommand (int i_register)
Brief.
Detailed
Parameters
\return
Definition at line 1111 of file IMUM6.cpp.
References b_command_complete, c_start_bits, p_imserial, and IMSerial::WriteData().
int IMUM6::SetCovarianceMatrixTransmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 587 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetDetailedSatelliteStatusTrasmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 465 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetEKFAccelerometerUpdates (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 848 of file IMUM6.cpp.
References i_misc_config_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_MISC_CONFIG.
int IMUM6::SetEKFMagnetometerUpdates (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 866 of file IMUM6.cpp.
References i_misc_config_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_MISC_CONFIG.
int IMUM6::SetEulerAngleTransmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 606 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetFrequency (int i_frequency)
Brief.
Detailed
Parameters
\return
Definition at line 295 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetGPSBaudrate (long l_baudrate)
Brief.
Detailed
Parameters
\return
Definition at line 404 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetGPSCourseVelocityTrasmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 506 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetGPSPositionTransmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 548 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetGPSRelativePositionTrasmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 528 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetGyroCalibration (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 830 of file IMUM6.cpp.
References i_misc_config_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_MISC_CONFIG.
int IMUM6::SetMode (bool b_mode)
Brief.
Detailed
Parameters
\return
Definition at line 767 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetPPSTiming (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 793 of file IMUM6.cpp.
References i_misc_config_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_MISC_CONFIG.
int IMUM6::SetProcessedAccelerometerTransmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 667 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetProcessedGyroTransmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 687 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetProcessedMagnetometerTransmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 647 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetQuaterninonState (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 811 of file IMUM6.cpp.
References i_misc_config_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_MISC_CONFIG.
int IMUM6::SetQuaternionTransmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 627 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetRawAccelerometerTransmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 727 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetRawGyroTransmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 747 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetRawMagnetometerTransmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 707 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetRegister16bitValue (int i_register, int16_t i_data) private
Brief.
Detailed
Parameters
\return
Definition at line 1025 of file IMUM6.cpp.
References IMUM6::UNION32::i, and SetRegister32bitValue().
int IMUM6::SetRegister16bitValue (int i_register, int16_t * p_i_data) private
Brief.
Detailed
Parameters
\return
Definition at line 1009 of file IMUM6.cpp.
References IMUM6::UNION32::i, and SetRegister32bitValue().
int IMUM6::SetRegister32bitValue (int i_register, float f_data) private
Brief.
Detailed
Parameters
\return
Definition at line 926 of file IMUM6.cpp.
References b_command_complete, IMUM6::UNION32::c, c_start_bits, IMUM6::UNION32::f, p_imserial, and IMSerial::WriteData().
Referenced by SetBaudRate(), SetCovarianceMatrixTransmission(), SetDetailedSatelliteStatusTrasmission(), SetEKFAccelerometerUpdates(), SetEKFMagnetometerUpdates(), SetEulerAngleTransmission(), SetFrequency(), SetGPSBaudrate(), SetGPSCourseVelocityTrasmission(), SetGPSPositionTransmission(), SetGPSRelativePositionTrasmission(), SetGyroCalibration(), SetMode(), SetPPSTiming(), SetProcessedAccelerometerTransmission(), SetProcessedGyroTransmission(), SetProcessedMagnetometerTransmission(), SetQuaterninonState(), SetQuaternionTransmission(), SetRawAccelerometerTransmission(), SetRawGyroTransmission(), SetRawMagnetometerTransmission(), SetRegister16bitValue(), SetSatelliteSummaryTrasmission(), and SetTemperatureMeasurementTransmission().
int IMUM6::SetRegister32bitValue (int i_register, int32_t i_data) private
Brief.
Detailed
Parameters
\return
Definition at line 967 of file IMUM6.cpp.
References b_command_complete, IMUM6::UNION32::c, c_start_bits, IMUM6::UNION32::i, p_imserial, and IMSerial::WriteData().
void IMUM6::SetRegisterPinValue (int32_t & i_register, int i_pin_no, int i_count_of_pins, char c_value) private
Brief.
Detailed
Parameters
\return
Definition at line 882 of file IMUM6.cpp.
Referenced by SetBaudRate(), SetCovarianceMatrixTransmission(), SetDetailedSatelliteStatusTrasmission(), SetEKFAccelerometerUpdates(), SetEKFMagnetometerUpdates(), SetEulerAngleTransmission(), SetFrequency(), SetGPSBaudrate(), SetGPSCourseVelocityTrasmission(), SetGPSPositionTransmission(), SetGPSRelativePositionTrasmission(), SetGyroCalibration(), SetMode(), SetPPSTiming(), SetProcessedAccelerometerTransmission(), SetProcessedGyroTransmission(), SetProcessedMagnetometerTransmission(), SetQuaterninonState(), SetQuaternionTransmission(), SetRawAccelerometerTransmission(), SetRawGyroTransmission(), SetRawMagnetometerTransmission(), SetSatelliteSummaryTrasmission(), and SetTemperatureMeasurementTransmission().
int IMUM6::SetSatelliteSummaryTrasmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 485 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
int IMUM6::SetTemperatureMeasurementTransmission (bool b_status)
Brief.
Detailed
Parameters
\return
Definition at line 568 of file IMUM6.cpp.
References i_communication_register, SetRegister32bitValue(), SetRegisterPinValue(), and IMUM6::REGISTERS::UM6_COMMUNICATION.
void IMUM6::StoreData () private
Brief.
Detailed
Parameters
\return
Definition at line 202 of file IMUM6.cpp.
References IMSerial::isReadyRead(), p_imserial, IMSerial::ReadData(), and T_c_stored_data.
Referenced by ParseData().
Member Data Documentation
bool IMUM6::b_command_complete private
Definition at line 952 of file IMUM6.h.
Referenced by IMUM6(), isCommandCompleted(), ProcessData(), SetCommand(), and SetRegister32bitValue().
bool IMUM6::b_incomplete_packet private
Definition at line 958 of file IMUM6.h.
Referenced by IMUM6(), and ParseData().
char IMUM6::c_input_buffer[500] private
Definition at line 950 of file IMUM6.h.
char IMUM6::c_start_bits[3] private
Definition at line 951 of file IMUM6.h.
Referenced by CheckData(), IMUM6(), ParseData(), SetCommand(), and SetRegister32bitValue().
int IMUM6::i_buffer_read_index private
Definition at line 962 of file IMUM6.h.
Referenced by IMUM6().
int32_t IMUM6::i_communication_register private
Definition at line 948 of file IMUM6.h.
Referenced by IMUM6(), SetBaudRate(), SetCovarianceMatrixTransmission(), SetDetailedSatelliteStatusTrasmission(), SetEulerAngleTransmission(), SetFrequency(), SetGPSBaudrate(), SetGPSCourseVelocityTrasmission(), SetGPSPositionTransmission(), SetGPSRelativePositionTrasmission(), SetMode(), SetProcessedAccelerometerTransmission(), SetProcessedGyroTransmission(), SetProcessedMagnetometerTransmission(), SetQuaternionTransmission(), SetRawAccelerometerTransmission(), SetRawGyroTransmission(), SetRawMagnetometerTransmission(), SetSatelliteSummaryTrasmission(), and SetTemperatureMeasurementTransmission().
int32_t IMUM6::i_data_registers[85] private
Definition at line 947 of file IMUM6.h.
Referenced by GetDataRegister(), and ProcessData().
int IMUM6::i_incomplete_no private
Definition at line 960 of file IMUM6.h.
Referenced by IMUM6(), and ParseData().
int32_t IMUM6::i_misc_config_register private
Definition at line 949 of file IMUM6.h.
Referenced by IMUM6(), SetEKFAccelerometerUpdates(), SetEKFMagnetometerUpdates(), SetGyroCalibration(), SetPPSTiming(), and SetQuaterninonState().
int IMUM6::i_start_bit_counter private
Definition at line 961 of file IMUM6.h.
Referenced by IMUM6(), and isReceivedData().
IMSerial* IMUM6::p_imserial private
Definition at line 964 of file IMUM6.h.
Referenced by IMUM6(), SetCommand(), SetRegister32bitValue(), and StoreData().
list<char> IMUM6::T_c_serial_log private
Definition at line 956 of file IMUM6.h.
list<char> IMUM6::T_c_stored_data private
Definition at line 955 of file IMUM6.h.
Referenced by isReceivedData(), ParseData(), and StoreData().
struct IMUM6::UM6_DATA IMUM6::um6_data
Referenced by CheckData(), GetRawData(), ParseData(), and ProcessData().
The documentation for this class was generated from the following files:
include/IMUM6.h
src/IMUM6.cpp