.TH "include/IMADC.h" 3 "Thu Jul 9 2015" "evarobot library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/IMADC.h \- 
Reads analog inputs through MCP3208 on evarobot sensorboard\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'IMSPI\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIMADC\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINCLUDE_IMADC_H_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reads analog inputs through MCP3208 on evarobot sensorboard\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehmet Akcakoca (mehmet.akcakoca@inovasyonmuhendislik.com) 
.RE
.PP
\fBDate:\fP
.RS 4
Mar, 2015
.RE
.PP
There are two types reading mode which are single-ended and differantial\&. Reference voltage in single-ended mode is 5V\&. Max\&. of adc bits is 16 bits\&. It is used for reading infrared sensors on evarobot\&. 
.PP
Definition in file \fBIMADC\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define INCLUDE_IMADC_H_"

.PP
Definition at line 33 of file IMADC\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for evarobot library from the source code\&.
