.TH "src/IMGPIO.cpp" 3 "Thu Jul 9 2015" "evarobot library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/IMGPIO.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/IMGPIO\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBg_b_exit_signal\fP = false"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "bool g_b_exit_signal = false"

.PP
Definition at line 16 of file IMGPIO\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for evarobot library from the source code\&.
