.TH "IMUM6::UM6_DATA" 3 "Thu Jul 9 2015" "evarobot library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMUM6::UM6_DATA \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IMUM6\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPACKET_TYPE\fP \fBpacket_type\fP"
.br
.ti -1c
.RI "char \fBc_PT\fP"
.br
.ti -1c
.RI "char \fBc_adress\fP"
.br
.ti -1c
.RI "char \fBc_databytes\fP [64]"
.br
.ti -1c
.RI "char \fBc_checksum\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file IMUM6\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char IMUM6::UM6_DATA::c_adress"

.PP
Definition at line 48 of file IMUM6\&.h\&.
.PP
Referenced by IMUM6::CheckData(), IMUM6::ParseData(), and IMUM6::ProcessData()\&.
.SS "char IMUM6::UM6_DATA::c_checksum[2]"

.PP
Definition at line 50 of file IMUM6\&.h\&.
.PP
Referenced by IMUM6::CheckData(), and IMUM6::ParseData()\&.
.SS "char IMUM6::UM6_DATA::c_databytes[64]"

.PP
Definition at line 49 of file IMUM6\&.h\&.
.PP
Referenced by IMUM6::CheckData(), IMUM6::ParseData(), and IMUM6::ProcessData()\&.
.SS "char IMUM6::UM6_DATA::c_PT"

.PP
Definition at line 47 of file IMUM6\&.h\&.
.PP
Referenced by IMUM6::CheckData(), and IMUM6::ParseData()\&.
.SS "\fBPACKET_TYPE\fP IMUM6::UM6_DATA::packet_type"

.PP
Definition at line 46 of file IMUM6\&.h\&.
.PP
Referenced by IMUM6::CheckData(), IMUM6::ParseData(), and IMUM6::ProcessData()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for evarobot library from the source code\&.
