.TH "include/IMUM6.h" 3 "Thu Jul 9 2015" "evarobot library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/IMUM6.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'IMSerial\&.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <list>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIMUM6\fP"
.br
.ti -1c
.RI "struct \fBIMUM6::PACKET_TYPE\fP"
.br
.ti -1c
.RI "struct \fBIMUM6::UM6_DATA\fP"
.br
.ti -1c
.RI "struct \fBIMUM6::REGISTERS\fP"
.br
.ti -1c
.RI "union \fBIMUM6::UNION32\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINCLUDE_IMUM6_H_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INCLUDE_IMUM6_H_"

.PP
Definition at line 23 of file IMUM6\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for evarobot library from the source code\&.
