.TH "IMUM6::UNION32" 3 "Thu Jul 9 2015" "evarobot library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMUM6::UNION32 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IMUM6\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBf\fP"
.br
.ti -1c
.RI "int32_t \fBi\fP"
.br
.ti -1c
.RI "unsigned char \fBc\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 788 of file IMUM6\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char IMUM6::UNION32::c[4]"

.PP
Definition at line 792 of file IMUM6\&.h\&.
.PP
Referenced by IMUM6::ProcessData(), and IMUM6::SetRegister32bitValue()\&.
.SS "float IMUM6::UNION32::f"

.PP
Definition at line 790 of file IMUM6\&.h\&.
.PP
Referenced by IMUM6::SetRegister32bitValue()\&.
.SS "int32_t IMUM6::UNION32::i"

.PP
Definition at line 791 of file IMUM6\&.h\&.
.PP
Referenced by IMUM6::ProcessData(), IMUM6::SetRegister16bitValue(), and IMUM6::SetRegister32bitValue()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for evarobot library from the source code\&.
