.TH "include Dizin Referansı" 3 "Per Tem 9 2015" "evarobot library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Dizin Referansı \- 
.SH SYNOPSIS
.br
.PP
.SS "Dosyalar"

.in +1c
.ti -1c
.RI "dosya \fBIMADC\&.h\fP"
.br
.RI "\fISensör Kartında bulunan analog girdileri okumaktadır\&. \fP"
.ti -1c
.RI "dosya \fBIMEIO\&.h\fP"
.br
.ti -1c
.RI "dosya \fBIMGPIO\&.h\fP"
.br
.RI "\fIRaspberry Pi üzerindeki GPIO'ları kontrol eden sınıftır\&. \fP"
.ti -1c
.RI "dosya \fBIMI2C\&.h\fP"
.br
.ti -1c
.RI "dosya \fBIMPWM\&.h\fP"
.br
.ti -1c
.RI "dosya \fBIMSerial\&.h\fP"
.br
.ti -1c
.RI "dosya \fBIMSPI\&.h\fP"
.br
.ti -1c
.RI "dosya \fBIMUM6\&.h\fP"
.br
.in -1c
