.TH "include/IMADC.h" 3 "Per Tem 9 2015" "evarobot library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/IMADC.h \- 
Sensör Kartında bulunan analog girdileri okumaktadır\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'IMSPI\&.h'\fP
.br

.SS "Sınıflar"

.in +1c
.ti -1c
.RI "class \fBIMADC\fP"
.br
.in -1c
.SS "Makrolar"

.in +1c
.ti -1c
.RI "#define \fBINCLUDE_IMADC_H_\fP"
.br
.in -1c
.SH "Ayrıntılı tanımlama"
.PP 
Sensör Kartında bulunan analog girdileri okumaktadır\&. 


.PP
\fBYazar:\fP
.RS 4
Mehmet Akcakoca (mehmet.akcakoca@inovasyonmuhendislik.com) 
.RE
.PP
\fBTarih:\fP
.RS 4
Mar, 2015
.RE
.PP
MCP3208 ADC üzerinden analog bilgileri okuyan sınıftır\&. Sensör Kartında bulunan analog girdileri okumaktadır\&. Maksimum 8 kanal okuyabilmektedir\&. Referans değeri 5V'tur\&. Pinler teker teker veya differansiyel olarak okunabilmektedir\&. Entegre ile SPI üzerinden haberleşilmektedir\&. Evarobot üzerindeki kızılötesi sensörleri okuyan sınıftır\&. 
.PP
\fBIMADC\&.h\fP dosyasında tanımlanmıştır\&.
.SH "Makro Dokümantasyonu"
.PP 
.SS "#define INCLUDE_IMADC_H_"

.PP
IMADC\&.h dosyasının 33 numaralı satırında tanımlanmıştır\&.
.SH "Yazar"
.PP 
Doxygen tarafındanevarobot library için kaynak koddan otomatik üretilmiştir\&.
