.TH "src/IMGPIO.cpp" 3 "Per Tem 9 2015" "evarobot library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/IMGPIO.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/IMGPIO\&.h'\fP
.br

.SS "Değişkenler"

.in +1c
.ti -1c
.RI "bool \fBg_b_exit_signal\fP = false"
.br
.in -1c
.SH "Değişken Dokümantasyonu"
.PP 
.SS "bool g_b_exit_signal = false"

.PP
IMGPIO\&.cpp dosyasının 16 numaralı satırında tanımlanmıştır\&.
.SH "Yazar"
.PP 
Doxygen tarafındanevarobot library için kaynak koddan otomatik üretilmiştir\&.
