.TH "include/IMI2C.h" 3 "Per Tem 9 2015" "evarobot library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/IMI2C.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <linux/i2c\&.h>\fP
.br
\fC#include <linux/i2c-dev\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/ipc\&.h>\fP
.br
\fC#include <semaphore\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br

.SS "Sınıflar"

.in +1c
.ti -1c
.RI "class \fBIMI2C\fP"
.br
.in -1c
.SS "Makrolar"

.in +1c
.ti -1c
.RI "#define \fBINCLUDE_IMI2C_H_\fP"
.br
.in -1c
.SH "Ayrıntılı tanımlama"
.PP 

.PP
\fBYazar:\fP
.RS 4
Mehmet Akcakoca (mehmet.akcakoca@inovasyonmuhendislik.com) 
.RE
.PP
\fBTarih:\fP
.RS 4
Mar, 2015 
.RE
.PP

.PP
\fBIMI2C\&.h\fP dosyasında tanımlanmıştır\&.
.SH "Makro Dokümantasyonu"
.PP 
.SS "#define INCLUDE_IMI2C_H_"

.PP
IMI2C\&.h dosyasının 23 numaralı satırında tanımlanmıştır\&.
.SH "Yazar"
.PP 
Doxygen tarafındanevarobot library için kaynak koddan otomatik üretilmiştir\&.
