.TH "IMUM6::UNION32" 3 "Per Tem 9 2015" "evarobot library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMUM6::UNION32 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IMUM6\&.h>\fP
.SS "Public Özellikler(attribute)"

.in +1c
.ti -1c
.RI "float \fBf\fP"
.br
.ti -1c
.RI "int32_t \fBi\fP"
.br
.ti -1c
.RI "unsigned char \fBc\fP [4]"
.br
.in -1c
.SH "Ayrıntılı tanımlama"
.PP 
IMUM6\&.h dosyasının 788 numaralı satırında tanımlanmıştır\&.
.SH "Üye Veri Dokümantasyonu"
.PP 
.SS "unsigned char IMUM6::UNION32::c[4]"

.PP
IMUM6\&.h dosyasının 792 numaralı satırında tanımlanmıştır\&.
.PP
Referans veren IMUM6::ProcessData() ve IMUM6::SetRegister32bitValue()\&.
.SS "float IMUM6::UNION32::f"

.PP
IMUM6\&.h dosyasının 790 numaralı satırında tanımlanmıştır\&.
.PP
Referans veren IMUM6::SetRegister32bitValue()\&.
.SS "int32_t IMUM6::UNION32::i"

.PP
IMUM6\&.h dosyasının 791 numaralı satırında tanımlanmıştır\&.
.PP
Referans veren IMUM6::ProcessData(), IMUM6::SetRegister16bitValue() ve IMUM6::SetRegister32bitValue()\&.

.SH "Yazar"
.PP 
Doxygen tarafındanevarobot library için kaynak koddan otomatik üretilmiştir\&.
