.TH "IMUM6::PACKET_TYPE" 3 "Per Tem 9 2015" "evarobot library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMUM6::PACKET_TYPE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IMUM6\&.h>\fP
.SS "Public Özellikler(attribute)"

.in +1c
.ti -1c
.RI "int \fBi_packet_has_data\fP"
.br
.ti -1c
.RI "int \fBi_packet_is_batch\fP"
.br
.ti -1c
.RI "int \fBi_batch_length\fP"
.br
.ti -1c
.RI "int \fBi_command_failed\fP"
.br
.ti -1c
.RI "int \fBi_size_of_data\fP"
.br
.in -1c
.SH "Ayrıntılı tanımlama"
.PP 
IMUM6\&.h dosyasının 35 numaralı satırında tanımlanmıştır\&.
.SH "Üye Veri Dokümantasyonu"
.PP 
.SS "int IMUM6::PACKET_TYPE::i_batch_length"

.PP
IMUM6\&.h dosyasının 39 numaralı satırında tanımlanmıştır\&.
.PP
Referans veren IMUM6::ParseData() ve IMUM6::ProcessData()\&.
.SS "int IMUM6::PACKET_TYPE::i_command_failed"

.PP
IMUM6\&.h dosyasının 40 numaralı satırında tanımlanmıştır\&.
.PP
Referans veren IMUM6::ParseData() ve IMUM6::ProcessData()\&.
.SS "int IMUM6::PACKET_TYPE::i_packet_has_data"

.PP
IMUM6\&.h dosyasının 37 numaralı satırında tanımlanmıştır\&.
.PP
Referans veren IMUM6::ParseData() ve IMUM6::ProcessData()\&.
.SS "int IMUM6::PACKET_TYPE::i_packet_is_batch"

.PP
IMUM6\&.h dosyasının 38 numaralı satırında tanımlanmıştır\&.
.PP
Referans veren IMUM6::ParseData() ve IMUM6::ProcessData()\&.
.SS "int IMUM6::PACKET_TYPE::i_size_of_data"

.PP
IMUM6\&.h dosyasının 41 numaralı satırında tanımlanmıştır\&.
.PP
Referans veren IMUM6::CheckData() ve IMUM6::ParseData()\&.

.SH "Yazar"
.PP 
Doxygen tarafındanevarobot library için kaynak koddan otomatik üretilmiştir\&.
